// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjyI1aKTnMGeaMEW1cx7733qg3esQmKGU',
    appId: '1:183181863177:web:6b323d3c33200d619e4bd8',
    messagingSenderId: '183181863177',
    projectId: 'bibliotecaflutter-14265',
    authDomain: 'bibliotecaflutter-14265.firebaseapp.com',
    storageBucket: 'bibliotecaflutter-14265.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDx5NXa1v31taTlTcenb3Mux2u2WpOYDRY',
    appId: '1:183181863177:android:b7dd2535d9535bbf9e4bd8',
    messagingSenderId: '183181863177',
    projectId: 'bibliotecaflutter-14265',
    storageBucket: 'bibliotecaflutter-14265.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm62pCdzouDzhpa0qZ8kwzaSCPmt9nttU',
    appId: '1:183181863177:ios:191b62a5da7641db9e4bd8',
    messagingSenderId: '183181863177',
    projectId: 'bibliotecaflutter-14265',
    storageBucket: 'bibliotecaflutter-14265.firebasestorage.app',
    iosBundleId: 'com.example.flutterBiblioteca',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm62pCdzouDzhpa0qZ8kwzaSCPmt9nttU',
    appId: '1:183181863177:ios:191b62a5da7641db9e4bd8',
    messagingSenderId: '183181863177',
    projectId: 'bibliotecaflutter-14265',
    storageBucket: 'bibliotecaflutter-14265.firebasestorage.app',
    iosBundleId: 'com.example.flutterBiblioteca',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjyI1aKTnMGeaMEW1cx7733qg3esQmKGU',
    appId: '1:183181863177:web:88131e8174996fbb9e4bd8',
    messagingSenderId: '183181863177',
    projectId: 'bibliotecaflutter-14265',
    authDomain: 'bibliotecaflutter-14265.firebaseapp.com',
    storageBucket: 'bibliotecaflutter-14265.firebasestorage.app',
  );
}
